### ISSUE TITLE
Cannot download the drum_transcriber.h5 model

### ISSUE THREAD

**Issue by brunoimbrizi** [yoshi-man/DrumTranscriber#1]
Hi @yoshi-man, I bumped into your excellent [article](https://pub.towardsai.net/building-an-audio-classification-model-for-automatic-drum-transcription-heres-what-i-learnt-a84f03d53413) yesterday and wanted to give DrumTranscriber a go, but I couldn't download drum_transcriber.h5. I followed these steps [How to retrieve GIT LFS files from GitHub](https://gist.github.com/fkraeutli/66fa741d9a8c2a6a238a01d17ed0edc5):
```
curl -X POST \
-H "Accept: application/vnd.git-lfs+json" \
-H "Content-type: application/json" \
-d '{"operation": "download", "transfer": ["basic"], "objects": [{"oid": "267f829291a7526951a8de3927ef5b80ba29d6ee38aadc2af786a0602c12cf46", "size": 682752720}]}' \
https://github.com/yoshi-man/DrumTranscriber.git/info/lfs/objects/batch
```
Which returned:
```
{
  "message": "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.",
  "documentation_url": "https://docs.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/"
}
```
Would it be okay for you to post the direct CDN link to the file?
Thank you.

**Comment by yoshi-man** [comment]
Hey @brunoimbrizi, thanks for spotting this. I've uploaded the model file to Google Drive instead for simplicity. Let me know if this fixes it!

https://drive.google.com/file/d/1w2fIHeyr-st3sbk1PYrtGOYW6YAD1fsi/view?usp=sharing

**Comment by brunoimbrizi** [comment]
Perfect! That worked, thank you for sharing.
