### ISSUE TITLE
python and modules versions

### ISSUE THREAD

**Issue by dci-student-jordan** [yoshi-man/DrumTranscriber#3]
Hi,

Thanks for sharing this. Could you please also share the versions of python and modules You were using creating the model? I tried to get it running with python 3.9, 3.10 and 3.11 but with no luck - output with 3.10.10:

AttributeError: Exception encountered when calling Flatten.call(). [1m'list' object has no attribute 'shape'[0m Arguments received by Flatten.call(): • args=(['<KerasTensor shape=(None, 6, 6, 1536), dtype=float32, sparse=False, name=keras_tensor_780>'],) • kwargs=<class 'inspect._empty'>

Also I would love to dig into creating my own model, though I'm a bloody newbe to AI, but - would you mind sharing your Dataset to get s.o. like me going? Please don't get me wrong, I just thought it might be worth asking...

Regards, Reini

**Comment by dci-student-jordan** [comment]
Ok, figured it out: with python 3.10.10, keras==2.11.0, and tensorflow==2.11.0 I got it running.

**Comment by yoshi-man** [comment]
Hey Reini, thanks for raising this up, and glad you have this solved. Have closed the issue now 😃
